---
- fail: msg="nfs_server_export is not defined"
  when: nfs_server_export == ''
- fail: msg="nfs_server_pool is not defined"
  when: nfs_server_pool == ''

- name: install nfs packages
  apt: update_cache=yes cache_valid_time=600 name=nfs-kernel-server,nfs-common state=latest
  sudo: yes
  tags:
    - nfs

- name: stop nfs
  service: name=nfs-kernel-server state=stopped
  sudo: yes
  tags:
    - nfs

- name: unmount existing volumes
  shell: umount {{ nfs_server_export }} || true
  sudo: yes
  tags:
    - nfs

- name: create root directory for NFS volume
  file: path={{ nfs_server_export }} state=directory
  sudo: yes
  tags:
    - nfs

- name: create sub directory for NFS volume
  file: path={{ nfs_server_export }} state=directory
  sudo: yes
  tags:
    - nfs

- name: create directory for NFS mount
  file: path={{ nfs_server_pool }} state=directory
  sudo: yes
  tags:
    - nfs

- name: mount NFS volume
  shell: mount --bind {{ nfs_server_pool }} {{ nfs_server_export }}
  sudo: yes
  tags:
    - nfs

- name: install /etc/exports
  template: src=exports dest=/etc/exports mode=0644
  sudo: yes
  tags:
    - nfs

- name: set nfsd options
  lineinfile:
    dest: /etc/default/nfs-kernel-server
    regexp: '^RPCNFSDOPTS=.*'
    line: 'RPCNFSDOPTS="{{ nfsdopts }}"'
  sudo: yes
  tags:
    - nfs

- name: start nfs
  service: name=nfs-kernel-server state=started
  sudo: yes
  tags:
    - nfs

#- name: restart idmapd
#  service: name=idmapd state=restarted
#  sudo: yes
#  tags:
#    - nfs
