---
- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  vars_files:
  - 'secrets.vault.yml'
  roles:
  - Datadog.datadog
  - common
  - docker

- hosts: proxy
  vars_files:
  - 'secrets.vault.yml'
  roles:
  - proxy

- hosts:
  - jupyterhub_host
  vars_files:
  - 'secrets.vault.yml'
  roles:
  - nfs_server

- hosts: jupyterhub_nodes
  serial: 100%
  vars_files:
  - 'secrets.vault.yml'
  roles:
  - nfs_client

- hosts: jupyterhub_host
  vars_files:
  - 'secrets.vault.yml'
  - 'users.vault.yml'
  roles:
  - swarm
  - restuser
  - jupyterhub
  - cull
  - stats
  - interact
