---
- fail: msg="nfsserver is not defined"
  when: nfsserver == ''
- fail: msg="nfsmount is not defined"
  when: nfsmount == ''

- name: install nfs client
  apt: update_cache=yes cache_valid_time=600 name=nfs-common state=present
  sudo: yes
  tags:
    - nfs

- name: unmount existing volumes
  shell: umount {{ nfsmount }} || true
  sudo: yes
  tags:
    - nfs

- name: configure /etc/fstab on clients
  mount: name={{ nfsmount }} src={{ nfsserver }}:{{ nfs_server_export }} fstype=nfs opts={{ nfsoptions }} state=mounted
  sudo: yes
  tags:
    - nfs
